# Site settings

title: Project Pages
header-img: img/header-img.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/testproject"
url: "http://JAGomberg.github.io"
github_username:  JAGomberg
project_repository: testproject

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
